apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-clc-snia.name" . }}-dbpg-creds
  annotations: {{ include "eric-clc-snia.common-annotations" . | nindent 4 }}
  labels: {{ include "eric-clc-snia.labels" . | nindent 4 }}
stringData:
  custom-user: senp-infra-db-user
  replica-user: replicauser
data:
  custom-user: c2VucC1pbmZyYS1kYi11c2VyCg==
  custom-pwd: MjY1dzZ4MG9yMHpSRiM4Lg==
  super-pwd: LnJ6RzdyMlRHdzEjQjdJYg==
  replica-user: cmVsaWNhLXVzZXI=
  replica-pwd: c0I4Lm5SMjFwVkZabzR6eQ==
  metrics-pwd: MlRvQTAwRlZXaWkuQmtiaA==